import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
				<div className="mx-auto max-w-screen-md min-h-screen bg-white  shadow-2xl border-x border-gray-100 flex flex-col">
            <main className="flex-1 w-full">
              {children}
            </main>
          </div>
      </body>
    </html>
  );
}
